const pptxgen = require("pptxgenjs");

let pres = new pptxgen();
pres.layout = "LAYOUT_16x9";
pres.title = "Smoke Test";

let slide = pres.addSlide();

// Dark blue background
slide.background = { color: "1A2C5B" };

// Centered white title
slide.addText("Hello World", {
  x: 0.5,
  y: 1.5,
  w: 9,
  h: 1.5,
  fontSize: 54,
  fontFace: "Calibri",
  bold: true,
  color: "FFFFFF",
  align: "center",
  valign: "middle",
});

// Subtitle below
slide.addText("Generated by pptxgenjs", {
  x: 0.5,
  y: 3.3,
  w: 9,
  h: 0.8,
  fontSize: 24,
  fontFace: "Calibri",
  color: "CADCFC",
  align: "center",
  valign: "middle",
});

pres
  .writeFile({ fileName: "outputs/smoketest-harness.pptx" })
  .then(() => console.log("Saved: outputs/smoketest-harness.pptx"))
  .catch((err) => { console.error(err); process.exit(1); });
