const pptxgen = require("pptxgenjs");

async function main() {
  const pres = new pptxgen();
  pres.layout = "LAYOUT_16x9";
  pres.title = "Smoke Test";

  const slide = pres.addSlide();
  slide.background = { color: "1B2A4A" };

  // Centered white title
  slide.addText("Hello World", {
    x: 0.5,
    y: 1.8,
    w: 9,
    h: 1.2,
    fontSize: 54,
    fontFace: "Calibri",
    bold: true,
    color: "FFFFFF",
    align: "center",
    valign: "middle",
  });

  // Subtitle below
  slide.addText("Generated by pptxgenjs", {
    x: 0.5,
    y: 3.2,
    w: 9,
    h: 0.7,
    fontSize: 24,
    fontFace: "Calibri",
    color: "CADCFC",
    align: "center",
    valign: "middle",
  });

  await pres.writeFile({ fileName: "outputs/smoketest-qa.pptx" });
  console.log("Written: outputs/smoketest-qa.pptx");
}

main().catch((err) => { console.error(err); process.exit(1); });
